require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 4.0.5
  SuggestExtensions: false
  Exclude:
    - .github
    - .kamal
    - bin/**/*
    - config/**/*
    - db/**/*
    - lib/tasks/*.rake
    - node_modules/**/*
    - public/**/*
    - tmp/**/*
    - log/**/*
    - vendor/**/*

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/LineLength:
  Max: 130

Metrics/ClassLength:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  # If `true`, strings which span multiple lines using `\` for continuation must
  # use the same type of quotes on each line.
  ConsistentQuotesInMultiline: false

Style/ClassAndModuleChildren:
  Enabled: false
