default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USER") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASS") { "postgres" } %>

development:
  <<: *default
  database: bloglify_development

test:
  <<: *default
  database: bloglify_test

production:
  primary: &primary_production
    <<: *default
    database: bloglify_production
    username: bloglify
    password: <%= ENV["BLOGLIFY_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: bloglify_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: bloglify_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: bloglify_production_cable
    migrations_paths: db/cable_migrate
